remote_theme: pages-themes/cayman@v0.2.0
title: DarthCoin Guides
description: Bitcoin and Lightning guides
url: "https://darth-coin.github.io/"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-relative-links
- jekyll-sitemap
- jekyll-feed
feed:
  icon: /assets/images/darthcoin-btc.png
  logo: /assets/images/darthcoin-door-btc.jpg