remote_theme: pages-themes/cayman@v0.2.0
url: "https://darth-coin.github.io/"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
- jekyll-relative-links
- jekyll-sitemap
title: DarthCoin Guides
description: Bitcoin and Lightning guides
